/* Generated By:JavaCC: Do not edit this line. CompilerConstants.java */
package Compiler;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CompilerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int IF_TOKEN = 5;
  /** RegularExpression Id. */
  int INT_TOKEN = 6;
  /** RegularExpression Id. */
  int VOID_TOKEN = 7;
  /** RegularExpression Id. */
  int ELSE_TOKEN = 8;
  /** RegularExpression Id. */
  int MAIN_TOKEN = 9;
  /** RegularExpression Id. */
  int WHILE_TOKEN = 10;
  /** RegularExpression Id. */
  int SCANF_TOKEN = 11;
  /** RegularExpression Id. */
  int PRINTF_TOKEN = 12;
  /** RegularExpression Id. */
  int RETURN_TOKEN = 13;
  /** RegularExpression Id. */
  int ID_TOKEN = 14;
  /** RegularExpression Id. */
  int NUM_TOKEN = 15;
  /** RegularExpression Id. */
  int COMMA_TOKEN = 16;
  /** RegularExpression Id. */
  int SEMICOLON_TOKEN = 17;
  /** RegularExpression Id. */
  int PLUS_TOKEN = 18;
  /** RegularExpression Id. */
  int MINUS_TOKEN = 19;
  /** RegularExpression Id. */
  int TIMES_TOKEN = 20;
  /** RegularExpression Id. */
  int DIVIDE_TOKEN = 21;
  /** RegularExpression Id. */
  int EQUAL_TOKEN = 22;
  /** RegularExpression Id. */
  int LBRACE_TOKEN = 23;
  /** RegularExpression Id. */
  int RBRACE_TOKEN = 24;
  /** RegularExpression Id. */
  int LPAREN_TOKEN = 25;
  /** RegularExpression Id. */
  int RPAREN_TOKEN = 26;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"if\"",
    "\"int\"",
    "\"void\"",
    "\"else\"",
    "\"main\"",
    "\"while\"",
    "\"scanf\"",
    "\"printf\"",
    "\"return\"",
    "<ID_TOKEN>",
    "<NUM_TOKEN>",
    "\",\"",
    "\";\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"=\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
  };

}
